### YamlMime:ManagedReference
items:
- uid: osu.Framework.Configuration
  commentId: N:osu.Framework.Configuration
  id: osu.Framework.Configuration
  children:
  - osu.Framework.Configuration.ConfigManager
  - osu.Framework.Configuration.ConfigManager`1
  - osu.Framework.Configuration.ConfigManager`1.TrackedSetting`1
  - osu.Framework.Configuration.DebugSetting
  - osu.Framework.Configuration.FrameSync
  - osu.Framework.Configuration.FrameworkConfigManager
  - osu.Framework.Configuration.FrameworkDebugConfigManager
  - osu.Framework.Configuration.FrameworkSetting
  - osu.Framework.Configuration.IConfigManager
  - osu.Framework.Configuration.IniConfigManager`1
  - osu.Framework.Configuration.RendererType
  - osu.Framework.Configuration.WindowMode
  langs:
  - csharp
  - vb
  name: osu.Framework.Configuration
  nameWithType: osu.Framework.Configuration
  fullName: osu.Framework.Configuration
  type: Namespace
  assemblies:
  - osu.Framework
references:
- uid: osu.Framework.Configuration.ConfigManager`1
  commentId: T:osu.Framework.Configuration.ConfigManager`1
  href: osu.Framework.Configuration.ConfigManager-1.html
  name: ConfigManager<TLookup>
  nameWithType: ConfigManager<TLookup>
  fullName: osu.Framework.Configuration.ConfigManager<TLookup>
  nameWithType.vb: ConfigManager(Of TLookup)
  fullName.vb: osu.Framework.Configuration.ConfigManager(Of TLookup)
  name.vb: ConfigManager(Of TLookup)
  spec.csharp:
  - uid: osu.Framework.Configuration.ConfigManager`1
    name: ConfigManager
    href: osu.Framework.Configuration.ConfigManager-1.html
  - name: <
  - name: TLookup
  - name: '>'
  spec.vb:
  - uid: osu.Framework.Configuration.ConfigManager`1
    name: ConfigManager
    href: osu.Framework.Configuration.ConfigManager-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TLookup
  - name: )
- uid: osu.Framework.Configuration.ConfigManager`1.TrackedSetting`1
  commentId: T:osu.Framework.Configuration.ConfigManager`1.TrackedSetting`1
  href: osu.Framework.Configuration.ConfigManager-1.html
  name: ConfigManager<TLookup>.TrackedSetting<TValue>
  nameWithType: ConfigManager<TLookup>.TrackedSetting<TValue>
  fullName: osu.Framework.Configuration.ConfigManager<TLookup>.TrackedSetting<TValue>
  nameWithType.vb: ConfigManager(Of TLookup).TrackedSetting(Of TValue)
  fullName.vb: osu.Framework.Configuration.ConfigManager(Of TLookup).TrackedSetting(Of TValue)
  name.vb: ConfigManager(Of TLookup).TrackedSetting(Of TValue)
  spec.csharp:
  - uid: osu.Framework.Configuration.ConfigManager`1
    name: ConfigManager
    href: osu.Framework.Configuration.ConfigManager-1.html
  - name: <
  - name: TLookup
  - name: '>'
  - name: .
  - uid: osu.Framework.Configuration.ConfigManager`1.TrackedSetting`1
    name: TrackedSetting
    href: osu.Framework.Configuration.ConfigManager-1.TrackedSetting-1.html
  - name: <
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: osu.Framework.Configuration.ConfigManager`1
    name: ConfigManager
    href: osu.Framework.Configuration.ConfigManager-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TLookup
  - name: )
  - name: .
  - uid: osu.Framework.Configuration.ConfigManager`1.TrackedSetting`1
    name: TrackedSetting
    href: osu.Framework.Configuration.ConfigManager-1.TrackedSetting-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TValue
  - name: )
- uid: osu.Framework.Configuration.ConfigManager
  commentId: T:osu.Framework.Configuration.ConfigManager
  parent: osu.Framework.Configuration
  href: osu.Framework.Configuration.ConfigManager.html
  name: ConfigManager
  nameWithType: ConfigManager
  fullName: osu.Framework.Configuration.ConfigManager
- uid: osu.Framework.Configuration.FrameSync
  commentId: T:osu.Framework.Configuration.FrameSync
  parent: osu.Framework.Configuration
  href: osu.Framework.Configuration.FrameSync.html
  name: FrameSync
  nameWithType: FrameSync
  fullName: osu.Framework.Configuration.FrameSync
- uid: osu.Framework.Configuration.FrameworkConfigManager
  commentId: T:osu.Framework.Configuration.FrameworkConfigManager
  parent: osu.Framework.Configuration
  href: osu.Framework.Configuration.FrameworkConfigManager.html
  name: FrameworkConfigManager
  nameWithType: FrameworkConfigManager
  fullName: osu.Framework.Configuration.FrameworkConfigManager
- uid: osu.Framework.Configuration.FrameworkSetting
  commentId: T:osu.Framework.Configuration.FrameworkSetting
  parent: osu.Framework.Configuration
  href: osu.Framework.Configuration.FrameworkSetting.html
  name: FrameworkSetting
  nameWithType: FrameworkSetting
  fullName: osu.Framework.Configuration.FrameworkSetting
- uid: osu.Framework.Configuration.FrameworkDebugConfigManager
  commentId: T:osu.Framework.Configuration.FrameworkDebugConfigManager
  parent: osu.Framework.Configuration
  href: osu.Framework.Configuration.FrameworkDebugConfigManager.html
  name: FrameworkDebugConfigManager
  nameWithType: FrameworkDebugConfigManager
  fullName: osu.Framework.Configuration.FrameworkDebugConfigManager
- uid: osu.Framework.Configuration.DebugSetting
  commentId: T:osu.Framework.Configuration.DebugSetting
  parent: osu.Framework.Configuration
  href: osu.Framework.Configuration.DebugSetting.html
  name: DebugSetting
  nameWithType: DebugSetting
  fullName: osu.Framework.Configuration.DebugSetting
- uid: osu.Framework.Configuration.IConfigManager
  commentId: T:osu.Framework.Configuration.IConfigManager
  parent: osu.Framework.Configuration
  href: osu.Framework.Configuration.IConfigManager.html
  name: IConfigManager
  nameWithType: IConfigManager
  fullName: osu.Framework.Configuration.IConfigManager
- uid: osu.Framework.Configuration.IniConfigManager`1
  commentId: T:osu.Framework.Configuration.IniConfigManager`1
  href: osu.Framework.Configuration.IniConfigManager-1.html
  name: IniConfigManager<TLookup>
  nameWithType: IniConfigManager<TLookup>
  fullName: osu.Framework.Configuration.IniConfigManager<TLookup>
  nameWithType.vb: IniConfigManager(Of TLookup)
  fullName.vb: osu.Framework.Configuration.IniConfigManager(Of TLookup)
  name.vb: IniConfigManager(Of TLookup)
  spec.csharp:
  - uid: osu.Framework.Configuration.IniConfigManager`1
    name: IniConfigManager
    href: osu.Framework.Configuration.IniConfigManager-1.html
  - name: <
  - name: TLookup
  - name: '>'
  spec.vb:
  - uid: osu.Framework.Configuration.IniConfigManager`1
    name: IniConfigManager
    href: osu.Framework.Configuration.IniConfigManager-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TLookup
  - name: )
- uid: osu.Framework.Configuration.RendererType
  commentId: T:osu.Framework.Configuration.RendererType
  parent: osu.Framework.Configuration
  href: osu.Framework.Configuration.RendererType.html
  name: RendererType
  nameWithType: RendererType
  fullName: osu.Framework.Configuration.RendererType
- uid: osu.Framework.Configuration.WindowMode
  commentId: T:osu.Framework.Configuration.WindowMode
  parent: osu.Framework.Configuration
  href: osu.Framework.Configuration.WindowMode.html
  name: WindowMode
  nameWithType: WindowMode
  fullName: osu.Framework.Configuration.WindowMode
- uid: osu.Framework.Configuration
  commentId: N:osu.Framework.Configuration
  href: osu.html
  name: osu.Framework.Configuration
  nameWithType: osu.Framework.Configuration
  fullName: osu.Framework.Configuration
  spec.csharp:
  - uid: osu
    name: osu
    href: osu.html
  - name: .
  - uid: osu.Framework
    name: Framework
    href: osu.Framework.html
  - name: .
  - uid: osu.Framework.Configuration
    name: Configuration
    href: osu.Framework.Configuration.html
  spec.vb:
  - uid: osu
    name: osu
    href: osu.html
  - name: .
  - uid: osu.Framework
    name: Framework
    href: osu.Framework.html
  - name: .
  - uid: osu.Framework.Configuration
    name: Configuration
    href: osu.Framework.Configuration.html
