### YamlMime:ManagedReference
items:
- uid: osu.Framework.Configuration.Tracking
  commentId: N:osu.Framework.Configuration.Tracking
  id: osu.Framework.Configuration.Tracking
  children:
  - osu.Framework.Configuration.Tracking.ITrackableConfigManager
  - osu.Framework.Configuration.Tracking.ITrackedSetting
  - osu.Framework.Configuration.Tracking.SettingDescription
  - osu.Framework.Configuration.Tracking.TrackedSetting`1
  - osu.Framework.Configuration.Tracking.TrackedSettings
  langs:
  - csharp
  - vb
  name: osu.Framework.Configuration.Tracking
  nameWithType: osu.Framework.Configuration.Tracking
  fullName: osu.Framework.Configuration.Tracking
  type: Namespace
  assemblies:
  - osu.Framework
references:
- uid: osu.Framework.Configuration.Tracking.ITrackableConfigManager
  commentId: T:osu.Framework.Configuration.Tracking.ITrackableConfigManager
  parent: osu.Framework.Configuration.Tracking
  href: osu.Framework.Configuration.Tracking.ITrackableConfigManager.html
  name: ITrackableConfigManager
  nameWithType: ITrackableConfigManager
  fullName: osu.Framework.Configuration.Tracking.ITrackableConfigManager
- uid: osu.Framework.Configuration.Tracking.ITrackedSetting
  commentId: T:osu.Framework.Configuration.Tracking.ITrackedSetting
  parent: osu.Framework.Configuration.Tracking
  href: osu.Framework.Configuration.Tracking.ITrackedSetting.html
  name: ITrackedSetting
  nameWithType: ITrackedSetting
  fullName: osu.Framework.Configuration.Tracking.ITrackedSetting
- uid: osu.Framework.Configuration.Tracking.SettingDescription
  commentId: T:osu.Framework.Configuration.Tracking.SettingDescription
  href: osu.Framework.Configuration.Tracking.SettingDescription.html
  name: SettingDescription
  nameWithType: SettingDescription
  fullName: osu.Framework.Configuration.Tracking.SettingDescription
- uid: osu.Framework.Configuration.Tracking.TrackedSetting`1
  commentId: T:osu.Framework.Configuration.Tracking.TrackedSetting`1
  href: osu.Framework.Configuration.Tracking.TrackedSetting-1.html
  name: TrackedSetting<TValue>
  nameWithType: TrackedSetting<TValue>
  fullName: osu.Framework.Configuration.Tracking.TrackedSetting<TValue>
  nameWithType.vb: TrackedSetting(Of TValue)
  fullName.vb: osu.Framework.Configuration.Tracking.TrackedSetting(Of TValue)
  name.vb: TrackedSetting(Of TValue)
  spec.csharp:
  - uid: osu.Framework.Configuration.Tracking.TrackedSetting`1
    name: TrackedSetting
    href: osu.Framework.Configuration.Tracking.TrackedSetting-1.html
  - name: <
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: osu.Framework.Configuration.Tracking.TrackedSetting`1
    name: TrackedSetting
    href: osu.Framework.Configuration.Tracking.TrackedSetting-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TValue
  - name: )
- uid: osu.Framework.Configuration.Tracking.TrackedSettings
  commentId: T:osu.Framework.Configuration.Tracking.TrackedSettings
  parent: osu.Framework.Configuration.Tracking
  href: osu.Framework.Configuration.Tracking.TrackedSettings.html
  name: TrackedSettings
  nameWithType: TrackedSettings
  fullName: osu.Framework.Configuration.Tracking.TrackedSettings
- uid: osu.Framework.Configuration.Tracking
  commentId: N:osu.Framework.Configuration.Tracking
  href: osu.html
  name: osu.Framework.Configuration.Tracking
  nameWithType: osu.Framework.Configuration.Tracking
  fullName: osu.Framework.Configuration.Tracking
  spec.csharp:
  - uid: osu
    name: osu
    href: osu.html
  - name: .
  - uid: osu.Framework
    name: Framework
    href: osu.Framework.html
  - name: .
  - uid: osu.Framework.Configuration
    name: Configuration
    href: osu.Framework.Configuration.html
  - name: .
  - uid: osu.Framework.Configuration.Tracking
    name: Tracking
    href: osu.Framework.Configuration.Tracking.html
  spec.vb:
  - uid: osu
    name: osu
    href: osu.html
  - name: .
  - uid: osu.Framework
    name: Framework
    href: osu.Framework.html
  - name: .
  - uid: osu.Framework.Configuration
    name: Configuration
    href: osu.Framework.Configuration.html
  - name: .
  - uid: osu.Framework.Configuration.Tracking
    name: Tracking
    href: osu.Framework.Configuration.Tracking.html
