### YamlMime:ManagedReference
items:
- uid: osu.Framework.Tests.Configuration
  commentId: N:osu.Framework.Tests.Configuration
  id: osu.Framework.Tests.Configuration
  children:
  - osu.Framework.Tests.Configuration.FrameworkConfigManagerTest
  - osu.Framework.Tests.Configuration.InputConfigManagerTest
  - osu.Framework.Tests.Configuration.InputConfigManagerTest.TestHeadlessGameHost
  langs:
  - csharp
  - vb
  name: osu.Framework.Tests.Configuration
  nameWithType: osu.Framework.Tests.Configuration
  fullName: osu.Framework.Tests.Configuration
  type: Namespace
  assemblies:
  - osu.Framework.Tests
references:
- uid: osu.Framework.Tests.Configuration.FrameworkConfigManagerTest
  commentId: T:osu.Framework.Tests.Configuration.FrameworkConfigManagerTest
  href: osu.Framework.Tests.Configuration.FrameworkConfigManagerTest.html
  name: FrameworkConfigManagerTest
  nameWithType: FrameworkConfigManagerTest
  fullName: osu.Framework.Tests.Configuration.FrameworkConfigManagerTest
- uid: osu.Framework.Tests.Configuration.InputConfigManagerTest
  commentId: T:osu.Framework.Tests.Configuration.InputConfigManagerTest
  href: osu.Framework.Tests.Configuration.InputConfigManagerTest.html
  name: InputConfigManagerTest
  nameWithType: InputConfigManagerTest
  fullName: osu.Framework.Tests.Configuration.InputConfigManagerTest
- uid: osu.Framework.Tests.Configuration.InputConfigManagerTest.TestHeadlessGameHost
  commentId: T:osu.Framework.Tests.Configuration.InputConfigManagerTest.TestHeadlessGameHost
  href: osu.Framework.Tests.Configuration.InputConfigManagerTest.html
  name: InputConfigManagerTest.TestHeadlessGameHost
  nameWithType: InputConfigManagerTest.TestHeadlessGameHost
  fullName: osu.Framework.Tests.Configuration.InputConfigManagerTest.TestHeadlessGameHost
  spec.csharp:
  - uid: osu.Framework.Tests.Configuration.InputConfigManagerTest
    name: InputConfigManagerTest
    href: osu.Framework.Tests.Configuration.InputConfigManagerTest.html
  - name: .
  - uid: osu.Framework.Tests.Configuration.InputConfigManagerTest.TestHeadlessGameHost
    name: TestHeadlessGameHost
    href: osu.Framework.Tests.Configuration.InputConfigManagerTest.TestHeadlessGameHost.html
  spec.vb:
  - uid: osu.Framework.Tests.Configuration.InputConfigManagerTest
    name: InputConfigManagerTest
    href: osu.Framework.Tests.Configuration.InputConfigManagerTest.html
  - name: .
  - uid: osu.Framework.Tests.Configuration.InputConfigManagerTest.TestHeadlessGameHost
    name: TestHeadlessGameHost
    href: osu.Framework.Tests.Configuration.InputConfigManagerTest.TestHeadlessGameHost.html
