#!/bin/bash
# generate_api_toc.sh
API_DIR=${1:-./api}
TOC_FILE="$API_DIR/toc.yml"

declare -A node_children
declare -A node_href

for md in "$API_DIR"/*.md; do
  filename=$(basename "$md" .md)
  [[ "$filename" == "toc" ]] && continue
  [[ "$filename" == "index" ]] && continue
  [[ "$filename" == "Home" ]] && continue

  if [[ ! "$filename" =~ ^osu\.Framework\. ]]; then
    continue
  fi

  remainder="${filename#osu.Framework.}"
  IFS='.' read -ra parts <<< "$remainder"

  current=""
  for part in "${parts[@]}"; do
    parent="$current"
    current="${current:+$current.}$part"

    if [[ -n "$parent" ]]; then
      if [[ ! " ${node_children[$parent]} " =~ " $current " ]]; then
        node_children["$parent"]+="$current "
      fi
    else
      if [[ ! " ${node_children[__root__]} " =~ " $current " ]]; then
        node_children["__root__"]+="$current "
      fi
    fi
  done

  node_href["$remainder"]="$filename.md"
done

print_node() {
  local node="$1"
  local indent="$2"
  local display="${node##*.}"
  local href="${node_href[$node]:-}"
  local children="${node_children[$node]:-}"

  echo "${indent}- name: $display" >> "$TOC_FILE"
  if [[ -n "$href" ]]; then
    echo "${indent}  href: $href" >> "$TOC_FILE"
  fi
  if [[ -n "$children" ]]; then
    echo "${indent}  items:" >> "$TOC_FILE"
    for child in $(echo "$children" | tr ' ' '\n' | sort); do
      print_node "$child" "$indent    "
    done
  fi
}

echo "# Auto-generated by generate_api_toc.sh" > "$TOC_FILE"
echo "- name: Home" >> "$TOC_FILE"
echo "  href: Home.md" >> "$TOC_FILE"
echo "  homepage: true" >> "$TOC_FILE"


for root in $(echo "${node_children[__root__]}" | tr ' ' '\n' | sort); do
  print_node "$root" ""
done
